export const business_unit_name_mapper = {
    BL: "Business Line",
    ABL: "Ancillary Business Line",
    CF: "Core Function",
};

export const riskCategoryMapper = [
    {
        pillar: "Operational",
        category: "Governance Risk",
        description: "The risk that the Group does not have appropriately robust controls, policies and procedures or segregation of duty protocols in place to prevent fraud or malfeasance either internally, externally or a combination thereof. Furthermore, it is also the risk that employees of the Group do not follow set controls, policies and procedures or segregation of duty protocols due to lack of knowledge, training or understanding of their importance.",
        riskAppetite: "Low",
        score: 1,
    },
    {
        pillar: "Operational",
        category: "Key Person/ Resourcing Risk",
        description: "The risk that the Group places substantial reliance on key individual(s) who support exclusively either the operations of a single or multiple DMS BUs, or a specific functional area that the Group relies heavily upon and as a result, the loss of knowledge, or potential detrimental actions of a key person, could expose the Group to one or more risks.",
        riskAppetite: "Medium",
        score: 2,
    },
    {
        pillar: "Operational",
        category: "Supervision of Third Parties Risk",
        description: "The risk that the Group, in relying on third parties to perform certain functions on their behalf and despite delivery being governed by contractual or service level agreements, the third party does not deliver on their contract or agreement.",
        riskAppetite: "Low",
        score: 1,
    },
    {
        pillar: "Operational",
        category: "Business Continuity Planning Risk",
        description: "The risk of a disaster either locally, globally or systemically, resulting in all or some of the Group operations ceasing and our inability to meet our contractual agreements or regulatory/ legal requirements.",
        riskAppetite: "Low",
        score: 1,
    },
    {
        pillar: "Operational",
        category: "Data Risk",
        description: "The risk of exposure to loss of value or reputation caused by issues or limitations to the Group’s ability to acquire, store, transform, move, and use its data.",
        riskAppetite: "Low",
        score: 1,
    },
    {
        pillar: "Operational",
        category: "IT/ Cybersecurity Risk",
        description: "The risk that external or internal person(s) can gain unauthorised access to the Group systems causing accidental or intentional damage, destruction, or loss of confidential, personal or proprietary data. Furthermore, the risk that the Group uses antiquated technology or applications critical to the construct, protection or maintenance of its IT infrastructure.",
        riskAppetite: "Low",
        score: 1,
    },
    {
        pillar: "Operational",
        category: "Geopolitical Risk",
        description: "The risk that a shift or paradigm change in the political climate in key jurisdictions can impact the Group and its businesses. This includes the risk of not identifying new risks that materialise as a result of the changing political environment.",
        riskAppetite: "High",
        score: 3,
    },
    {
        pillar: "Financial",
        category: "Finance Risk",
        description: "The risk that the Groups means to earn revenue is reduced or removed and/or clients do not pay fees due in a timely manner or fail to do so (either singly or when combined with other factors, such as liquidity considerations or adverse actions impacting tax planning), resulting in the Group being unable to meet some or all of its financial commitments.",
        riskAppetite: "Low",
        score: 1,
    },
    {
        pillar: "Financial",
        category: "Regulatory Capital Risk",
        description: "The risk that the Group is no longer able to support the retention of the requisite regulatory capital of one or more of its regulated businesses.",
        riskAppetite: "Low(Zero Tolerance)",
        score: 1,
    },
    {
        pillar: "Financial",
        category: "Insurance Risk",
        description: "The risk to the financial stability of the Group should any party take a claim against it and where there is insufficient insurance to cover such a claim.",
        riskAppetite: "Low",
        score: 1,
    },
    {
        pillar: "Financial",
        category: "New Business / Product Risk",
        description: "The risk that the Group does not fully understand and prepare for a new business or product resulting in noncompliance, poor governance, failure to satisfy reasonable expectation of a client or other negative impact.",
        riskAppetite: "Medium",
        score: 2,
    },
    {
        pillar: "Financial",
        category: "Market Risk",
        description: "The risk that global market movements or movements in the markets in which the Group operates, negatively impacts the income of the Group. Market movements can be due to a combination of adverse changes in factors such as regulation, technology, geo-political and client preferences.",
        riskAppetite: "Medium",
        score: 2,
    },
    {
        pillar: "Financial",
        category: "Currency Risk",
        description: "The risk that currency exposure increases as the Group grows in Europe while the base currency is USD. ",
        riskAppetite: "Medium",
        score: 2,
    },
    {
        pillar: "Financial",
        category: "Strategic Risk",
        description: "The risk that due to external and/or internal factors the Group is not able to execute their medium or long-term Business Strategy.",
        riskAppetite: "Medium",
        score: 2,
    },
    {
        pillar: "Financial",
        category: "Reputational Risk",
        description: "The risk that the reputation of the Group or its businesses is damaged from negative publicity, public perception or uncontrollable events, adversely impacting the Groups revenue.",
        riskAppetite: "Low",
        score: 1,
    },
    {
        pillar: "Regulatory",
        category: "Compliance Risk",
        description: "The risk that the Group is not fulfilling all of its existing regulatory and compliance requirements or is unprepared for the future applicable regulation. ",
        riskAppetite: "Low(Zero Tolerance)",
        score: 1,
    },
    {
        pillar: "Regulatory",
        category: "Regulatory Change Risk",
        description: "The risk that changes to the regulatory environments in which the Group operates, impacts current product offerings by preventing the Group from offering such products or making products or locations less attractive to clients.",
        riskAppetite: "Medium",
        score: 2,
    },
    {
        pillar: "Regulatory",
        category: "Anti Money Laundering & CTF Risk",
        description: "The risk that AML (including Sanctions)  and CTF (including Proliferation Financing)  requirements have not been appropriately applied by the Group in relation to its clients. This risk also applies to third parties acting on the Group’s behalf where the Group ultimately retains responsibility.",
        riskAppetite: "Low(Zero Tolerance)",
        score: 1,
    },
    {
        pillar: "Regulatory",
        category: "Legal Risk",
        description: "The risk that the Groups third-party contracts are not robust enough to ensure that any adverse financial, regulatory and operational impacts are appropriately mitigated.",
        riskAppetite: "Low",
        score: 1,
    },
    {
        pillar: "Core Function",
        category: "AML COE Team Risk",
        description: "The AML COE Team manages the AML, CTF and Sanctions requirements for the Group. The risk is that the AML Centre of Excellence Team are unable to effectively carry out of their day to day operations.",
        riskAppetite: "Low",
        score: 1,
    },
    {
        pillar: "Core Function",
        category: "Compliance Team Risk",
        description: "The Group has regulated businesses across multiple jurisdictions that are required to comply with relevant legislation. The risk is that the Global Compliance Team are unable to effectively carry out their function of overseeing the compliance with the relevant legislation.",
        riskAppetite: "Low",
        score: 1,
    },
    {
        pillar: "Core Function",
        category: "IT Team Risk",
        description: "The Group has a centralised Global IT Team providing services across the Group. The risk is that if the IT Team are unable to effectively carry out of their day to day operations this may negatively impact the Group.",
        riskAppetite: "Low",
        score: 1,
    },
    {
        pillar: "Core Function",
        category: "HR Team Risk",
        description: "The Group has a centralised Global HR Team responsible for resourcing, succession planning and other HR matters across the Group. The risk is that if the HR Team are unable to effectively carry out of their day to day operations this may negatively impact the Group.",
        riskAppetite: "Medium",
        score: 2,
    },
    {
        pillar: "Core Function",
        category: "Finance Team Risk",
        description: "The Group has a centralised Global Finance Team responsible for the financial reporting, requirements and other financial matters of the Group. The risk is that if the Finance Team are unable to effectively carry out of their day to day operations this may negatively impact the Group.",
        riskAppetite: "Low",
        score: 1,
    },
    {
        pillar: "Core Function",
        category: "Business Development Team Risk",
        description: "The Group has a global Business Development Team that operates as the main point of sale and new business/client entry into the Group. Thus, the risk to the Group is that this team engages with a new individual, entity or asset class in contravention of Groups policy. ",
        riskAppetite: "Low",
        score: 1,
    },
    {
        pillar: "Core Function",
        category: "Audit Team Risk",
        description: "Both the Internal and External Audit Team provide the Group with the third line of defence in relation to risk and compliance matters. The risk is that the Internal and External Audit Teams are unable to effectively carry out their function of assuring the Group of compliance.",
        riskAppetite: "Low",
        score: 1,
    },
];

export const ratingMapper = [
    {
        impact: "High",
        likelihood: "Unlikely",
        rating: "Significant (3A)",
        Appetite: "Appetite: Medium",
        score: 3,
    },
    {
        impact: "High",
        likelihood: "Possible",
        rating: "Material (3B)",
        Appetite: "Appetite: High",
        score: 6,
    },
    {
        impact: "High",
        likelihood: "Likely",
        rating: "Material (3C)",
        Appetite: "Appetite: High",
        score: 9,
    },
    {
        impact: "Medium",
        likelihood: "Unlikely",
        rating: "Important (2A)",
        Appetite: "Appetite: Medium",
        score: 2,
    },
    {
        impact: "Medium",
        likelihood: "Possible",
        rating: "Important (2B)",
        Appetite: "Appetite: Medium",
        score: 4,
    },
    {
        impact: "Medium",
        likelihood: "Likely",
        rating: "Significant (2C)",
        Appetite: "Appetite: Medium",
        score: 6,
    },
    {
        impact: "Low",
        likelihood: "Unlikely",
        rating: "Minor (1A)",
        Appetite: "Appetite: Low(zero tolerance)",
        score: 1,
    },
    {
        impact: "Low",
        likelihood: "Possible",
        rating: "Minor (1B)",
        Appetite: "Appetite: Low",
        score: 2,
    },
    {
        impact: "Low",
        likelihood: "Likely",
        rating: "Minor (1C)",
        Appetite: "Appetite: Low",
        score: 3,
    },
];
